development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: whosaid_development
  pool: 5
  username: <%= `whoami`.chomp %>
  password:

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: whosaid_test
  pool: 5
  username: <%= `whoami`.chomp %>
  password:

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: whosaid
  pool: 5
  username:
  password:
